### ISSUE TITLE
[Story] Duplicate Machine

### ISSUE THREAD

**Issue by kiraashton** [HypercubeMafia/ADAM#11]
As a student I would like to duplicate a machine so I can modify a machine without changing the original

**Comment by kiraashton** [comment]
Acceptance test 
1) Start on the machine select page 
2) Click the options button on the sample DFA machine card 
3) Select the duplicate option
4) Enter a name for the new machine
5) Verify that you see a new machine card with that title

**Comment by iracigt** [comment]
Merged by PR #40.
