### ISSUE TITLE
[Task] View machine

### ISSUE THREAD

**Issue by kiraashton** [HypercubeMafia/ADAM#27]
When a user opens a machine, it should display a (static) view of a machine.

**Comment by iracigt** [comment]
When this task is complete, a user should be able to:

1) Start on the machine select page
2) Choose a machine by clicking on its card
3) Verify it navigates to a machine specific page
4) Verify the new page shows an image of a machine

Note: For this task, the machine shown may not match the machine name and may even be a different type of machine.
