### ISSUE TITLE
[Task] New Machine Button Creates New Machine

### ISSUE THREAD

**Issue by maeichho** [HypercubeMafia/ADAM#8]

**Comment by maeichho** [comment]
When this task is complete, a user should be able to:
(1) Start on the machine select page.
(2) Click the new machine button.
(3) Verify that a new machine was added to the list.

**Comment by iracigt** [comment]
Attempted to run task test. Fails to load with following error:

![Screen Shot 2018-09-22 at 8.11.17 PM.png](https://images.zenhubusercontent.com/5b9c09d9a55bf40b51d40c40/18c4d95e-f4d3-4f26-972e-71d5673ff263)
